trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'Azure Container Registry'
  dockerfilePath: './Dockerfile'
  imageName: 'studioworks/avscanner-api:$(Build.BuildId)'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageName)'
    dockerfile: '$(dockerfilePath)'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: 'AvScanner.Api/AvScanner.Api.csproj'
    feedsToUse: 'select'
    vstsFeed: 'kangmike'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'AvScanner.Api/AvScanner.Api.csproj'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: 'AvScanner.Api.Tests/AvScanner.Api.Tests.csproj'
    configuration: '$(buildConfiguration)'
    nobuild: true
    arguments: '--collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: 'AvScanner.Api/AvScanner.Api.csproj'
    configuration: '$(buildConfiguration)'
    publishWebProjects: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
