trigger:
- master

variables:
- group: 'YourVariableGroup'  # Replace with the name of your variable group

stages:
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'outputVariables'
        downloadPath: '$(System.ArtifactsDirectory)/outputVariables'

    - powershell: |
        $buildVersion = Get-Content "$(System.ArtifactsDirectory)/outputVariables/buildVersion"
        Write-Host "Using buildVersion: $buildVersion"
        echo "##vso[task.setvariable variable=buildVersion]$buildVersion"
      displayName: 'Set Release Variable'

    - task: AzureCLI@2
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: '<Your Azure Subscription>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Use the release variable in your deployment script
          az webapp config container set \
            --name av-scanner \
            --resource-group test \
            --docker-custom-image-name studioworks.azurecr.io/microservice-av-scanner:$(buildVersion)

      # Add more tasks as needed for your deployment
