trigger:
- master

variables:
- group: 'YourVariableGroup'  # Replace with the name of your variable group

stages:
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: '<Your Azure Subscription>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Use the release variable in your deployment script
          az webapp config container set \
            --name av-scanner \
            --resource-group test \
            --docker-custom-image-name studioworks.azurecr.io/microservice-av-scanner:$(Build.BuildNumber)
          # Set the environment variable
          az webapp config appsettings set \
            --name av-scanner \
            --resource-group test \
            --settings ASPNETCORE_ENVIRONMENT=dev  # Replace with your desired environment value
